jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Checkout content
        uses: actions/checkout@v3
        with:
          repository: mdn/content
          path: content
      - name: Checkout translated-content
        uses: actions/checkout@v3
        with:
          repository: webdoky/content
          path: translated-content
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        name: Update issue
        run: |
          python3 script.py
name: Update issue
on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 5,17 * * *"
