jobs:
  get-analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./get-analytics/requirements.txt
      - env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        name: Get analytics
        run: |
          python3 ./get-analytics/run.py
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: analytics
          path: ./_Pages.json

  predict:
    needs: [get-analytics]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get analytics
        uses: actions/download-artifact@v4
        with:
          name: analytics
          path: ./_Pages.json
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./predict/requirements.txt
      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: mdn/content
          path: content
      - name: Checkout translated-content
        uses: actions/checkout@v4
        with:
          repository: webdoky/content
          path: translated-content
          depth: 0
      - name: Predict
        run: |
          python3 ./predict/run.py
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: predictions
          path: ./_Prediction.json
  edit-issue:
    needs: [predict]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./edit-issue/requirements.txt
      - name: Get predictions
        uses: actions/download-artifact@v4
        with:
          name: predictions
          path: .
      - name: Edit issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 ./edit-issue/run.py
name: Update issue
on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 5,17 * * *"
